openapi: 3.1.0
x-stoplight:
  id: pwoavfbz2gvxz
info:
  title: ApiCurrenciesExchange
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /currenciesexchange:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "msg": "La Moneda Cambio ha sido Guardado Exitosamente.",
                    "MonedaCambioID": 16,
                    "FechaHoraUsuario": "2022-12-21T18:16:05.159",
                    "NombreUsuario": "ADMINISTRADOR"
                }
            }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: |-
            {
                "statusCode": 400,
                "message": "Ya existe un registro en la Fecha actual."
            }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  MonedaCambioID: ''
                  MonedaID: '10'
                  CambioVenta: '25'
                  CambioCompra: '30'
                  Fecha: '20221226'
                  Cambio: '20'
              properties:
                MonedaCambioID:
                  type: number
                MonedaID:
                  type: number
                CambioVenta:
                  type: number
                CambioCompra:
                  type: number
                Fecha:
                  type: string
                Cambio:
                  type: number
              required:
                - MonedaID
                - Fecha
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNjYzODM4LCAiZXhwIjoxNjcxNjcxMDM4IH0.tZwZqX-wA9jJXozIGslCoklLmNRLJrIE_wfbLy9JhAo
          in: header
          name: accessToken
          description: Token de Validaci贸n.
          required: true
    parameters: []
  '/currenciesexchange/{monedaCambioID}':
    parameters:
      - schema:
          type: string
        name: monedaCambioID
        in: path
        required: true
    put:
      summary: ''
      operationId: put-currenciesexchange-monedaCambioID
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "msg": "La Moneda Cambio se ha modificado exitosamente"
                }
            }
        '400':
          description: |-
            {
                "statusCode": 400,
                "message": "Ya existe un registro en la Fecha actual."
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNjYzODM4LCAiZXhwIjoxNjcxNjcxMDM4IH0.tZwZqX-wA9jJXozIGslCoklLmNRLJrIE_wfbLy9JhAo
          in: header
          name: accessToken
          description: Token de Validaci贸n.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  MonedaCambioID: ''
                  MonedaID: '10'
                  CambioVenta: '25'
                  CambioCompra: '30'
                  Fecha: '20221226'
                  Cambio: '20'
              properties:
                MonedaCambioID:
                  type: number
                MonedaID:
                  type: number
                CambioVenta:
                  type: number
                CambioCompra:
                  type: number
                Fecha:
                  type: string
                Cambio:
                  type: number
              required:
                - MonedaCambioID
                - MonedaID
                - Fecha
    delete:
      summary: ''
      operationId: delete-currenciesexchange-monedaCambioID
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "msg": "La Moneda Cambio ha sido Eliminada exitosamente."
                }
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNjYzODM4LCAiZXhwIjoxNjcxNjcxMDM4IH0.tZwZqX-wA9jJXozIGslCoklLmNRLJrIE_wfbLy9JhAo
          in: header
          name: accessToken
          description: Token de Validaci贸n.
          required: true
  '/currenciesexchange/{monedaID}':
    parameters:
      - schema:
          type: string
        name: monedaID
        in: path
        required: true
    get:
      summary: ''
      operationId: get-currenciesexchange-monedaID
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "sql": "SELECT * \r\nFROM MonedaCambio \r\nWHERE MonedaCambio.MonedaID = 9 AND \r\nMonedaCambio.CustomerID = 29",
                    "records": [
                        {
                            "MonedaCambioID": 10,
                            "MonedaID": 9,
                            "UsuarioID": 1,
                            "FechaHoraUsuario": "2022-12-21T16:19:32.245",
                            "CambioVenta": 25,
                            "CambioCompra": 30,
                            "Fecha": "20220102",
                            "Cambio": 20
                        },
                        {
                            "MonedaCambioID": 9,
                            "MonedaID": 9,
                            "UsuarioID": 13,
                            "FechaHoraUsuario": "2022-12-21T16:17:37.659",
                            "CambioVenta": 2,
                            "CambioCompra": 3,
                            "Fecha": "20221213",
                            "Cambio": 1
                        }
                    ]
                }
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNjYzODM4LCAiZXhwIjoxNjcxNjcxMDM4IH0.tZwZqX-wA9jJXozIGslCoklLmNRLJrIE_wfbLy9JhAo
          in: header
          name: accessToken
          description: Token de Validaci贸n.
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
