openapi: 3.1.0
x-stoplight:
  id: 13j8r1zfdbfnn
info:
  title: ApiMain
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/municipalities/light/{provinciaID}':
    get:
      summary: findManyByProvinceLight
      tags: []
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "records": [
                        {
                            "municipioid": 8148,
                            "nombre": "Dosquebradas",
                            "codigo": "170"
                        },
                        {
                            "municipioid": 8149,
                            "nombre": "Pereira",
                            "codigo": "001"
                        }
                    ]
                }
            }
      operationId: get-municipalities-light
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: 'accessToken '
          description: tokenReciente
    parameters:
      - schema:
          type: string
        name: provinciaID
        in: path
        required: true
        description: '53'
  '/municipalities/{provinciaID}':
    get:
      summary: findManyByProvince
      tags: []
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "records": [
                        {
                            "municipioid": 8148,
                            "nombre": "Dosquebradas",
                            "codigo": "170"
                        }
                    ]
                }
            }
      operationId: 'get-http:-localhost:8026-municipalities'
      parameters:
        - schema:
            type: string
          in: header
          name: 'accessToken '
          description: '"tokenReciente"'
        - schema:
            type: string
          in: query
          name: 'param '
          description: dos
    parameters:
      - schema:
          type: string
        name: provinciaID
        in: path
        required: true
        description: '53'
  /municipality/checkMunicipality:
    get:
      summary: checkMunicipality
      tags: []
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "sCodigoPostal": "001",
                    "sIDCodigoPostal": 14768,
                    "MunicipioID": 8149,
                    "MunicipioNombre": "Pereira"
                }
            }
      operationId: get-municipality-checkMunicipality
      parameters:
        - schema:
            type: string
          in: header
          name: 'accessToken '
          description: '"tokenReciente"'
        - schema:
            type: integer
          in: query
          name: paisID
          description: '45'
        - schema:
            type: string
          in: query
          name: sMunicipio
          description: 'pereira '
  /postalcode/checkPostalCode:
    get:
      summary: checkPostalCode
      tags: []
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "codigoPostalID": 14768,
                    "codigoPostal": "001",
                    "municipioID": 8149,
                    "municipioNombre": "Pereira"
                }
            }
      operationId: get-postalcode-checkPostalCode
      parameters:
        - schema:
            type: string
          in: header
          name: 'accessToken '
          description: '"tokenReciente"'
        - schema:
            type: integer
          in: query
          name: paisID
          description: '45'
        - schema:
            type: string
          in: query
          name: codigoPostal
          description: '001'
  /grid:
    parameters: []
    post:
      summary: Grid - Save
      operationId: post-grid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      success:
                        type: boolean
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiY3Rva2VuIjoiIiwgImlhdCI6MTY4Mzc0ODI0MiwgImV4cCI6MTY4NzM0ODI0MiB9.M_FMJvkv5MI7CA-NCeaoLG3t5Drrk6omxgxClx4dhRE
          in: header
          name: accessToken
          description: Token de autenticación.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  header:
                    nombrePage: PAGE_AddOffers
                    nombreControl: TABLE_TableOffers
                    aplicarAnchor: 1
                  lines:
                    - nombreColumna: COL_Stock
                      orden: 2
                      ancho: 140
                      titulo: Stock Total
                    - nombreColumna: COL_Linea
                      orden: 3
                      ancho: 150
                      titulo: Línea
              properties:
                header:
                  type: object
                  required:
                    - nombrePage
                    - nombreControl
                  properties:
                    nombrePage:
                      type: string
                    nombreControl:
                      type: string
                    aplicarAnchor:
                      type: integer
                lines:
                  type: array
                  items:
                    type: object
                    properties:
                      nombreColumna:
                        type: string
                      orden:
                        type: integer
                      ancho:
                        type: integer
                      titulo:
                        type: string
                    required:
                      - nombreColumna
              required:
                - header
            examples:
              Example 1:
                value:
                  header:
                    nombrePage: string
                    nombreControl: string
                    aplicarAnchor: 0
                  lines:
                    - nombreColumna: string
                      orden: 0
                      ancho: 0
                      titulo: string
  /continents:
    get:
      summary: Continents - FindAll
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      success:
                        type: boolean
                      sql:
                        type: string
                      records:
                        type: array
                        items:
                          type: object
                          properties:
                            ContinenteID:
                              type: integer
                            Nombre:
                              type: string
                            CustomerID:
                              type: integer
                            UsuarioID:
                              type: integer
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      sql: "SELECT * FROM Continente\r\nWHERE Continente.CustomerID = 29"
                      records:
                        - ContinenteID: 1
                          Nombre: Africa
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 2
                          Nombre: America
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 3
                          Nombre: Asia
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 4
                          Nombre: Europa
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 5
                          Nombre: Oceania
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 6
                          Nombre: Antártida
                          CustomerID: 29
                          UsuarioID: 1
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      sql: "SELECT * FROM Continente\r\nWHERE Continente.CustomerID = 29"
                      records:
                        - ContinenteID: 1
                          Nombre: Africa
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 2
                          Nombre: America
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 3
                          Nombre: Asia
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 4
                          Nombre: Europa
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 5
                          Nombre: Oceania
                          CustomerID: 29
                          UsuarioID: 1
                        - ContinenteID: 6
                          Nombre: Antártida
                          CustomerID: 29
                          UsuarioID: 1
      operationId: get-continents
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcyMzQ5MTcyLCAiZXhwIjoxNjcyMzU2MzcyIH0._R6egSIjKnI-OMeQjVs5tz7Jk4vJSIdk7Wh22SyJomg
          in: header
          name: accessToken
          description: Token de acceso. Si no se cuenta con uno no se podrá realizar la petición.
          required: true
components:
  schemas: {}
