openapi: 3.1.0
x-stoplight:
  id: za2vqlcecgdtw
info:
  title: ApiMethodsOfPaymentAndCollection
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /methodsofpaymentandcollection:
    post:
      summary: Create
      operationId: post-user
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "msg": "La Forma de Pago/Cobro se ha Guardado exitosamente.",
                    "FormaPagoCobroID": 12,
                    "FechaHoraUsuario": "2022-12-22T19:09:02.963",
                    "NombreUsuario": "ADMINISTRADOR"
                }
            }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: |-
            {
                "statusCode": 400,
                "message": "El Código introducido ya existe. Por favor introduzca otro Código."
            }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  FormaPagoCobroID: ''
                  Codigo: Tivis
                  Nombre: Formas de Tiv
                  Reclamable: '1'
                  CobroAutomatico: '1'
                  Negociable: '0'
                  PorcentajeDtoProntoPago: '11'
                  PorcentajeGastoFinanciero: '12'
                  CodigoExterno: T
                  Abreviatura: T
              properties:
                FormaPagoCobroID:
                  type: string
                Codigo:
                  type: string
                Nombre:
                  type: string
                Reclamable:
                  type: number
                CobroAutomatico:
                  type: number
                Negociable:
                  type: number
                PorcentajeDtoProntoPago:
                  type: number
                PorcentajeGastoFinanciero:
                  type: number
                CodigoExterno:
                  type: string
                Abreviatura:
                  type: string
              required:
                - Codigo
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNzU0MDE4LCAiZXhwIjoxNjcxNzYxMjE4IH0.JD0j7PTqTFgXGP-pgdVdXrphh0hNFINK1Nkm9mtyKcc
          in: header
          name: accessToken
          description: Token de Validación.
          required: true
    parameters: []
    get:
      summary: FindAll
      operationId: get-methodsofpaymentandcollection
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "sql": "SELECT * FROM formapagocobro\r\nWHERE formapagocobro.CustomerID = 29",
                    "records": [
                        {
                            "FormaPagoCobroID": 5,
                            "Codigo": "01",
                            "UsuarioID": 1,
                            "FechaHoraUsuario": "2020-08-12T10:30:33.772",
                            "Nombre": "EFECTIVO",
                            "Reclamable": 0,
                            "CobroAutomatico": 0,
                            "Negociable": 0,
                            "PorcentajeDtoProntoPago": 0,
                            "PorcentajeGastoFinanciero": 0,
                            "CodigoExterno": "VIS",
                            "Abreviatura": ""
                        },
                        {
                            "FormaPagoCobroID": 6,
                            "Codigo": "03",
                            "UsuarioID": 1,
                            "FechaHoraUsuario": "2020-08-12T10:31:21.547",
                            "Nombre": "TRANSFERENCIA",
                            "Reclamable": 0,
                            "CobroAutomatico": 0,
                            "Negociable": 0,
                            "PorcentajeDtoProntoPago": 0,
                            "PorcentajeGastoFinanciero": 0,
                            "CodigoExterno": "MET",
                            "Abreviatura": ""
                        },
                        {
                            "FormaPagoCobroID": 7,
                            "Codigo": "02",
                            "UsuarioID": 1,
                            "FechaHoraUsuario": "2020-08-12T10:31:43.629",
                            "Nombre": "CHEQUE",
                            "Reclamable": 0,
                            "CobroAutomatico": 0,
                            "Negociable": 0,
                            "PorcentajeDtoProntoPago": 0,
                            "PorcentajeGastoFinanciero": 0,
                            "CodigoExterno": "",
                            "Abreviatura": ""
                        },
                        {
                            "FormaPagoCobroID": 8,
                            "Codigo": "04",
                            "UsuarioID": 1,
                            "FechaHoraUsuario": "2020-08-12T10:32:18.935",
                            "Nombre": "TARJETA DE CREDITO",
                            "Reclamable": 0,
                            "CobroAutomatico": 0,
                            "Negociable": 0,
                            "PorcentajeDtoProntoPago": 0,
                            "PorcentajeGastoFinanciero": 0,
                            "CodigoExterno": "",
                            "Abreviatura": ""
                        },
                        {
                            "FormaPagoCobroID": 12,
                            "Codigo": "El Tivis",
                            "UsuarioID": 1,
                            "FechaHoraUsuario": "2022-12-22T19:09:02.963",
                            "Nombre": "Forms",
                            "Reclamable": 0,
                            "CobroAutomatico": 0,
                            "Negociable": 1,
                            "PorcentajeDtoProntoPago": 16,
                            "PorcentajeGastoFinanciero": 17,
                            "CodigoExterno": "TTT",
                            "Abreviatura": "TTT"
                        }
                    ]
                }
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNzU0MDE4LCAiZXhwIjoxNjcxNzYxMjE4IH0.JD0j7PTqTFgXGP-pgdVdXrphh0hNFINK1Nkm9mtyKcc
          in: header
          name: accessToken
          description: Token de Validación.
          required: true
  '/methodsofpaymentandcollection/{formaPagoCobroID}':
    parameters:
      - schema:
          type: string
        name: formaPagoCobroID
        in: path
        required: true
    put:
      summary: Update
      operationId: put-methodsofpaymentandcollection-formaPagoCobroID
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "msg": "La Forma de Pago/Cobro se ha modificado exitosamente."
                }
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNzU0MDE4LCAiZXhwIjoxNjcxNzYxMjE4IH0.JD0j7PTqTFgXGP-pgdVdXrphh0hNFINK1Nkm9mtyKcc
          in: header
          name: accesToken
          description: Token de validación.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  FormaPagoCobroID: ''
                  Codigo: El Tivis
                  Nombre: Forms
                  Reclamable: '0'
                  CobroAutomatico: '0'
                  Negociable: '1'
                  PorcentajeDtoProntoPago: '16'
                  PorcentajeGastoFinanciero: '17'
                  CodigoExterno: TTT
                  Abreviatura: TTT
              properties:
                FormaPagoCobroID:
                  type: number
                Codigo:
                  type: string
                Nombre:
                  type: string
                Reclamable:
                  type: number
                CobroAutomatico:
                  type: number
                Negociable:
                  type: number
                PorcentajeDtoProntoPago:
                  type: number
                PorcentajeGastoFinanciero:
                  type: number
                CodigoExterno:
                  type: string
                Abreviatura:
                  type: string
              required:
                - FormaPagoCobroID
                - Codigo
        description: ''
    delete:
      summary: Remove
      operationId: delete-methodsofpaymentandcollection-formaPagoCobroID
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "msg": "La Forma de Pago/Cobro ha sido Eliminada exitosamente."
                }
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcxNzU0MDE4LCAiZXhwIjoxNjcxNzYxMjE4IH0.JD0j7PTqTFgXGP-pgdVdXrphh0hNFINK1Nkm9mtyKcc
          in: header
          name: accessToken
          description: Token de validación.
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
