openapi: 3.0.0
x-stoplight:
  id: 6a74499413cbf
info:
  version: '1.0'
  title: ApiOffers
  description: ''
servers:
  - description: Direccion Francia
    url: 'http://15.236.85.216/'
paths:
  /offers:
    post:
      summary: Create
      operationId: post-offers
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "ofertaID": 2186,
                    "numero": 2181,
                    "version": 1,
                    "fechaCreacion": "2022-11-16T16:13:31.866",
                    "usuarioCreacion": "ADMINISTRADOR",
                    "estado": "",
                    "MotivoRechazoID": 0,
                    "rechazoDescripcion": ""
                }
            }
        '400':
          description: |-
            {
                "statusCode": 400,
                "message": "Usuario Inactivo"
            }
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |-
          {
              "cabecera": {
                  "ofertaID": "",
                  "almacenID": "",
                  "fechaEntrega": "",
                  "mailingID": "",
                  "numeroSolicitud": "",
                  "fechaSolicitud": "",
                  "TransportistaID": "",
                  "PlataformaLogisticaMailingID": "",
                  "TarifaVentaID": "",
                  "fechaHoraUsuario": "",
                  "representanteID": "",
                  "contactoID": "",
                  "telefonoCuenta": "",
                  "direccionEnvioID": "",
                  "observaciones": "",
                  "notaCliente": "",
                  "responsableUsuarioID": "",
                  "tipoOfertaID": "",
                  "respresentante2ID": "",
                  "porcentajeComision": "",
                  "porcentajeComision2": "",
                  "referenciaInterna": "",
                  "FechaSolcitadaPara": "",
                  "idionaID": "",
                  "fecha": "",
                  "validoDesde": "",
                  "fechaValidez": "",
                  "inconterm": "",
                  "campanaID": "",
                  "oportunidadID": ""
              },
              "intrastat": {
                  "CondicionEntregaID": ""
              },
              "cualificacion": {
                  "EstrategiaID": "",
                  "RentabilidadID": "",
                  "OportunidadID": "",
                  "InteresID": "",
                  "AtencionID": "",
                  "SituacionID": "",
                  "DedicacionMaxima": ""
              },
              "facturacion": {
              "ClienteFacturaID": "", 
              "FormaPagoCobroID": "", 
              "NumeroVencimiento": "", 
              "DiasPrimerVencimiento": "", 
              "DiasResto": "", 
              "DiasFijoPago1": "", 
              "DiasFijoPago2": "", 
              "DiasFijoPago3": "", 
              "DiasFijoPago4": "", 
              "MesVacacion": "", 
              "DiaSiguientePago": "", 
              "PorcentajeDtoComercial1": "", 
              "PorcentajeDtoComercial2": "", 
              "PorcentajeDtoComercial3": "", 
              "PorcentajeDtoEspecial1": "", 
              "PorcentajeDtoEspecial2": "", 
              "PorcentajeDtoProntoPago": "", 
              "PorcentajeGastoFinanciero": "", 
              "MonedaID": "", 
              "MonedaCambio": "", 
              "Portes": ""
              }
          }
    parameters: []
    get:
      summary: FindMany
      operationId: get-offers
      responses:
        '200':
          description: |-
            {
                "statusCode": 500,
                "message": "Token invalid: Malformed"
            }
      parameters:
        - schema:
            type: number
            example: 0
          in: query
          name: offset
          description: 'Registro a partir del cual empezará a traer los datos desde la tabla. Si se envía por ejemplo 20, y en la tabla existen 100 registros, la respuesta traerá solo los registros comprendidos entre las posiciones 20 y 100, y los primero 20 se omitirán.'
          required: true
        - schema:
            type: number
            example: 50
          in: query
          name: limit
          description: 'Límite de registros que trae la consulta. Si se envía por ejemplo el número 50, si la tabla tiene 2000 registros solo se traerán 50.'
          required: true
        - schema:
            type: string
            example: '1'
          in: query
          name: order
          description: 'Esta valor determina si los registros de leerán desde arriba hacia abajo, o desde abajo hacia arriba en la tabla. Si por ejemplo la tabla cuenta con 100 registros'
          required: true
  '/offers/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: id de la oferta
    get:
      summary: FindOne
      tags: []
      responses: {}
      operationId: get-offers-id
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
  /login:
    post:
      summary: Login
      operationId: post-login
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  description: 'Example: admin@admin.com'
                pass:
                  type: string
              required:
                - user
                - pass
            examples:
              Example:
                value:
                  user: admin@admin.com
                  pass: 0nyx2021
        description: |-
          {
              "user": "admin@admin.com",
              "pass": "0nyx2021"
          }
  '/offers/{offerid}/lines':
    parameters:
      - schema:
          type: string
        name: offerid
        in: path
        required: true
    get:
      summary: FindLinesByOffer
      tags: []
      responses: {}
      operationId: get-offers-offerid-lines
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
      description: ''
    post:
      summary: CreateLine
      operationId: post-offers-offerid-lines
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |-
          {
              "ofertaLineaID": "",
              "linea": "",
              "almacenid": "",
              "articuloid": "",
              "nombre": "",
              "descripcion": "",
              "referencia": "",
              "cantidad": "",
              "precioVenta": "",
              "dto1": "",
              "dto2": "",
              "dto3": "",
              "importeVenta": "",
              "cantidad2": "",
              "notaInterna": "",
              "notaCliente": "",
              "ivaid": "",
              "ofertaID": "",
              "nivelIngenieriaID": "",
              "fechaEntrega": "",
              "plazoEntrega": "",
              "tipoPlazoEntregaID": "",
              "referenciaCliente": ""
          }
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
components:
  parameters:
    token:
      name: token
      in: header
      description: Token de autenticación
      schema:
        type: string
        example: eyAic2lnIjoiSFMyNTYiLCAidHlwIjoiSldUIiB9.eyAidXNlcklEIjo0NCwgImN1c3RvbWVySUQiOjI5LCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJlZGdvcyIsICJhZG1pbmlzdHJhZG9yIjp0cnVlLCAiZW1wcmVzYUlEIjoxLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjQ5MjU0ODMyLCAiZXhwIjoxNjQ5MjYyMDMyIH0.rNNdNm9MflATkqiE6tA_HOCb8BmMX6uleG1I_TY7AkU
      required: true
  schemas: {}
