openapi: 3.0.0
x-stoplight:
  id: pin4ntmffj2a3
info:
  version: '1.0'
  title: ApiSales
  description: ''
servers:
  - description: Direccion Francia
    url: 'http://15.236.85.216/'
paths: {}
components:
  parameters:
    token:
      name: token
      in: header
      description: Token de autenticación
      schema:
        type: string
        example: eyAic2lnIjoiSFMyNTYiLCAidHlwIjoiSldUIiB9.eyAidXNlcklEIjo0NCwgImN1c3RvbWVySUQiOjI5LCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJlZGdvcyIsICJhZG1pbmlzdHJhZG9yIjp0cnVlLCAiZW1wcmVzYUlEIjoxLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjQ5MjU0ODMyLCAiZXhwIjoxNjQ5MjYyMDMyIH0.rNNdNm9MflATkqiE6tA_HOCb8BmMX6uleG1I_TY7AkU
      required: true
  schemas: {}
