openapi: 3.1.0
x-stoplight:
  id: 6s61w68jtcf1x
info:
  title: ApiSales
  version: '1.0'
servers:
  - url: 'http://15.236.85.216/'
paths:
  /sales/orders/:
    post:
      summary: Create SaleOrder
      operationId: post-sales-orders
      responses:
        '200':
          description: |-
            {
                "statusCode": 200,
                "message": "Request processed successfully",
                "content": {
                    "success": true,
                    "idPedidoVenta": 2183,
                    "numero": 72
                }
            }
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjY4NjI1NjkxLCAiZXhwIjoxNjY4NjMyODkxIH0.E0EcErEPyLZAYu55hZi-3Eoz3O0tQzm4yJmzdAl-alk
          in: header
          name: accessToken
          description: Token de acceso. Si no se cuenta con uno no se podrá realizar la petición.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pedidoVentaData:
                  type: object
                  properties:
                    pedidoVentaCabeceraID:
                      type: string
                    SeriePedidoID:
                      type: string
                    fecha:
                      type: string
                    ClienteID:
                      type: string
                    ReferenciaCliente:
                      type: string
                    FechaCaptacion:
                      type: string
                    FechaEntregaPrevistaInterna:
                      type: string
                    FechaEntregaPrevistaCliente:
                      type: string
                    DireccionEnvioID:
                      type: string
                    AlmacenID:
                      type: string
                    TipoPedidoID:
                      type: string
                    ClienteFacturaID:
                      type: string
                    FormaPagoID:
                      type: string
                    Confirmado:
                      type: string
                    AlbaranNoValorado:
                      type: string
                    MonedaID:
                      type: string
                    MonedaCambio:
                      type: string
                    Portes:
                      type: string
                    ImportePortes:
                      type: string
                    ImporteOtroGasto:
                      type: string
                    IvaID:
                      type: string
                    TarifaVentaID:
                      type: string
                    PedidoPor:
                      type: string
                    NumeroVencimiento:
                      type: string
                    DiasPrimerVencimiento:
                      type: string
                    DiasResto:
                      type: string
                    DiaFijoPago1:
                      type: string
                    DiaFijoPago2:
                      type: string
                    DiaFijoPago3:
                      type: string
                    DiaFijoPago4:
                      type: string
                    MesVacacion:
                      type: string
                    DiaSiguientePago:
                      type: string
                    PorcentajeDtoComercial1:
                      type: string
                    PorcentajeDtoComercial2:
                      type: string
                    PorcentaDtoComercial3:
                      type: string
                    PorcentajeDtoProntoPago:
                      type: string
                    PorcentajeDtoEspecial1:
                      type: string
                    PorcentajeDtoEspecial2:
                      type: string
                    PorcentajeGastoFinanciero:
                      type: string
                    NumeroCopiasAlbaran:
                      type: string
                    NumeroCopiasFactura:
                      type: string
                    AgruparAlbaran:
                      type: string
                    BancoClienteID:
                      type: string
                    Iban:
                      type: string
                    descripcion:
                      type: string
                    notaCliente:
                      type: string
                    notaGeneral:
                      type: string
              x-examples:
                Example 1:
                  pedidoVentaData:
                    pedidoVentaCabeceraID: ''
                    SeriePedidoID: ''
                    fecha: ''
                    ClienteID: ''
                    ReferenciaCliente: ''
                    FechaCaptacion: ''
                    FechaEntregaPrevistaInterna: ''
                    FechaEntregaPrevistaCliente: ''
                    DireccionEnvioID: ''
                    AlmacenID: ''
                    TipoPedidoID: ''
                    ClienteFacturaID: ''
                    FormaPagoID: ''
                    Confirmado: ''
                    AlbaranNoValorado: ''
                    MonedaID: ''
                    MonedaCambio: ''
                    Portes: ''
                    ImportePortes: ''
                    ImporteOtroGasto: ''
                    IvaID: ''
                    TarifaVentaID: ''
                    PedidoPor: ''
                    NumeroVencimiento: ''
                    DiasPrimerVencimiento: ''
                    DiasResto: ''
                    DiaFijoPago1: ''
                    DiaFijoPago2: ''
                    DiaFijoPago3: ''
                    DiaFijoPago4: ''
                    MesVacacion: ''
                    DiaSiguientePago: ''
                    PorcentajeDtoComercial1: ''
                    PorcentajeDtoComercial2: ''
                    PorcentaDtoComercial3: ''
                    PorcentajeDtoProntoPago: ''
                    PorcentajeDtoEspecial1: ''
                    PorcentajeDtoEspecial2: ''
                    PorcentajeGastoFinanciero: ''
                    NumeroCopiasAlbaran: ''
                    NumeroCopiasFactura: ''
                    AgruparAlbaran: ''
                    BancoClienteID: ''
                    Iban: ''
                    descripcion: ''
                    notaCliente: ''
                    notaGeneral: ''
            examples:
              Example 1:
                value:
                  pedidoVentaData:
                    pedidoVentaCabeceraID: string
                    SeriePedidoID: string
                    fecha: string
                    ClienteID: string
                    ReferenciaCliente: string
                    FechaCaptacion: string
                    FechaEntregaPrevistaInterna: string
                    FechaEntregaPrevistaCliente: string
                    DireccionEnvioID: string
                    AlmacenID: string
                    TipoPedidoID: string
                    ClienteFacturaID: string
                    FormaPagoID: string
                    Confirmado: string
                    AlbaranNoValorado: string
                    MonedaID: string
                    MonedaCambio: string
                    Portes: string
                    ImportePortes: string
                    ImporteOtroGasto: string
                    IvaID: string
                    TarifaVentaID: string
                    PedidoPor: string
                    NumeroVencimiento: string
                    DiasPrimerVencimiento: string
                    DiasResto: string
                    DiaFijoPago1: string
                    DiaFijoPago2: string
                    DiaFijoPago3: string
                    DiaFijoPago4: string
                    MesVacacion: string
                    DiaSiguientePago: string
                    PorcentajeDtoComercial1: string
                    PorcentajeDtoComercial2: string
                    PorcentaDtoComercial3: string
                    PorcentajeDtoProntoPago: string
                    PorcentajeDtoEspecial1: string
                    PorcentajeDtoEspecial2: string
                    PorcentajeGastoFinanciero: string
                    NumeroCopiasAlbaran: string
                    NumeroCopiasFactura: string
                    AgruparAlbaran: string
                    BancoClienteID: string
                    Iban: string
                    descripcion: string
                    notaCliente: string
                    notaGeneral: string
      description: ''
    parameters: []
  '/sales/orders/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-sales-orders
      responses:
        '200':
          description: OK
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
