openapi: 3.1.0
x-stoplight:
  id: h3n8zpb8rs93d
info:
  title: ApiTokens_Account
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tokens/token_id:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-tokens-token_id
      x-stoplight:
        id: w3uraooxymrz9
    post:
      summary: ''
      operationId: post-tokens-token_id
      responses:
        '200':
          description: OK
      x-stoplight:
        id: bw9dkl44usymf
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token_id:
                  $ref: '#/components/schemas/User'
                  x-stoplight:
                    id: rhah9xlwud0n1
                token:
                  type: integer
                  x-stoplight:
                    id: rgdwseptm0oep
                  format: int32
                  readOnly: true
                expiration:
                  type: string
                  x-stoplight:
                    id: tfikotz0s8zyj
                  format: date-time
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: aqzfxbj4qcw5q
        firstName:
          type: string
          x-stoplight:
            id: 05gci2j5we9nb
        lastName:
          type: string
          x-stoplight:
            id: d0mcjzi7msnuv
        email:
          type: string
          format: email
          x-stoplight:
            id: a9mm21eyjtgf9
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: peyczey46fqv1
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: 7uvacdaczmhl9
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 2xgi0wqa2s13c
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: u8cbvqv90fkua
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
security:
  - API Key - 1: []
