openapi: 3.1.0
x-stoplight:
  id: ao55w1ipt665j
info:
  title: ApiVehicles
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /consult/vehicles:
    get:
      summary: Vehicle - findManyByFilters
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      records:
                        type: array
                        items:
                          type: object
                          properties:
                            NombreVersion:
                              type: string
                            NombreModelo:
                              type: string
                            NombreTipoVehiculo:
                              type: string
                            NombreCombustible:
                              type: string
                            Codigo:
                              type: string
                      success:
                        type: boolean
                      sql:
                        type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      records:
                        - NombreVersion: '1.6'
                          NombreModelo: Clio
                          NombreTipoVehiculo: ''
                          NombreCombustible: ''
                          Codigo: '1'
                        - NombreVersion: ''
                          NombreModelo: ''
                          NombreTipoVehiculo: ''
                          NombreCombustible: ''
                          Codigo: '231231'
                      success: true
                      sql: "SELECT Vehiculo.*,\r\nVersion.Nombre AS NombreVersion,\r\nModelo.Nombre AS NombreModelo,\r\nMarca.Nombre AS NombreMarca,\r\nTipoVehiculo.Descripcion AS NombreTipoVehiculo,\r\nCombustible.Descripcion AS NombreCombustible \r\nFROM Vehiculo\r\nLEFT OUTER JOIN Version ON Version.VersionID = Vehiculo.VersionID\r\nLEFT OUTER JOIN Modelo ON Modelo.ModeloID = Version.ModeloID\r\nLEFT OUTER JOIN Marca ON Marca.MarcaID = Modelo.MarcaID\r\nLEFT OUTER JOIN TablaGeneral AS TipoVehiculo ON TipoVehiculo.TablaGeneralID = Vehiculo.TipoVehiculoID\r\nLEFT OUTER JOIN TablaGeneral AS Combustible ON Combustible.TablaGeneralID = Vehiculo.CombustibleID\r\nWHERE Vehiculo.CustomerID = 29\r\nAND Vehiculo.EmpresaID = 1\r\n\r\nlimit 50 \r\noffset 0"
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      records:
                        - NombreVersion: '1.6'
                          NombreModelo: Clio
                          NombreTipoVehiculo: ''
                          NombreCombustible: ''
                          Codigo: '1'
                        - NombreVersion: ''
                          NombreModelo: ''
                          NombreTipoVehiculo: ''
                          NombreCombustible: ''
                          Codigo: '231231'
                      success: true
                      sql: "SELECT Vehiculo.*,\r\nVersion.Nombre AS NombreVersion,\r\nModelo.Nombre AS NombreModelo,\r\nMarca.Nombre AS NombreMarca,\r\nTipoVehiculo.Descripcion AS NombreTipoVehiculo,\r\nCombustible.Descripcion AS NombreCombustible \r\nFROM Vehiculo\r\nLEFT OUTER JOIN Version ON Version.VersionID = Vehiculo.VersionID\r\nLEFT OUTER JOIN Modelo ON Modelo.ModeloID = Version.ModeloID\r\nLEFT OUTER JOIN Marca ON Marca.MarcaID = Modelo.MarcaID\r\nLEFT OUTER JOIN TablaGeneral AS TipoVehiculo ON TipoVehiculo.TablaGeneralID = Vehiculo.TipoVehiculoID\r\nLEFT OUTER JOIN TablaGeneral AS Combustible ON Combustible.TablaGeneralID = Vehiculo.CombustibleID\r\nWHERE Vehiculo.CustomerID = 29\r\nAND Vehiculo.EmpresaID = 1\r\n\r\nlimit 50 \r\noffset 0"
      operationId: get-consult-vehicles
      parameters:
        - schema:
            type: string
          in: header
          name: 'accessToken '
          description: '"tokenReciente"'
        - schema:
            type: string
          in: query
          name: offset
          description: '0'
        - schema:
            type: string
          in: query
          name: limit
          description: '50'
        - schema:
            type: string
          in: query
          name: codVehiculoDesde
        - schema:
            type: string
          in: query
          name: codVehiculoHasta
        - schema:
            type: string
          in: query
          name: matricula
        - schema:
            type: string
          in: query
          name: tipo
        - schema:
            type: string
          in: query
          name: marcaVehiculo
        - schema:
            type: string
          in: query
          name: modeloVehiculo
        - schema:
            type: string
          in: query
          name: versionVehiculo
  /brand/light:
    get:
      summary: Vehicle - findLightListBrand
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      success:
                        type: boolean
                      records:
                        type: array
                        items:
                          type: object
                          properties:
                            MarcaID:
                              type: integer
                            Nombre:
                              type: string
                      sql:
                        type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      records:
                        - MarcaID: 1
                          Nombre: Renault
                        - MarcaID: 2
                          Nombre: VW
                        - MarcaID: 3
                          Nombre: Audi
                        - MarcaID: 4
                          Nombre: Mercedes
                      sql: "SELECT * \r\nFROM Marca\r\nWHERE Marca.CustomerID = 29\r\nAND Marca.EmpresaID = 1\r\n"
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      records:
                        - MarcaID: 1
                          Nombre: Renault
                        - MarcaID: 2
                          Nombre: VW
                        - MarcaID: 3
                          Nombre: Audi
                        - MarcaID: 4
                          Nombre: Mercedes
                      sql: "SELECT * \r\nFROM Marca\r\nWHERE Marca.CustomerID = 29\r\nAND Marca.EmpresaID = 1\r\n"
      operationId: get-brand-light
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: '"tokenReciente"'
components:
  schemas: {}
