openapi: 3.1.0
x-stoplight:
  id: 09mafsaf81kyl
info:
  title: API - Warehouse
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /warehouse:
    get:
      summary: FindManyByParam
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      success:
                        type: boolean
                      sql:
                        type: string
                      records:
                        type: array
                        items:
                          type: object
                          properties:
                            AlmacenID:
                              type: integer
                            Codigo:
                              type: string
                            Nombre:
                              type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      sql: "SELECT *\r\n\r\nFROM\r\nAlmacen\r\n\r\nWHERE\r\nAlmacen.CustomerID = 29 AND\r\nAlmacen.EmpresaID = 1 AND\r\nAlmacen.Disponible = 1\r\nAND (Almacen.Nombre LIKE '%silo%' OR Almacen.Codigo LIKE '%silo%')\r\nORDER BY Almacen.AlmacenID \r\nLIMIT 10 "
                      records:
                        - AlmacenID: 5
                          Codigo: SA01
                          Nombre: Silos Maiz 01
                        - AlmacenID: 6
                          Codigo: SF01
                          Nombre: Silo Forraje 01JUJJU
                        - AlmacenID: 7
                          Codigo: SS01
                          Nombre: Silo Semola 01
                        - AlmacenID: 39
                          Codigo: SA02
                          Nombre: Silos Maiz 02
                        - AlmacenID: 40
                          Codigo: SA03
                          Nombre: Silos Maiz 03
                        - AlmacenID: 41
                          Codigo: SA04
                          Nombre: Silos Maiz 04
                        - AlmacenID: 42
                          Codigo: SA05
                          Nombre: Silos Maiz 05
                        - AlmacenID: 43
                          Codigo: SA06
                          Nombre: Silos Maiz 06
                        - AlmacenID: 44
                          Codigo: SA07
                          Nombre: Silos Maiz 07
                        - AlmacenID: 46
                          Codigo: SS02
                          Nombre: Silo Semola 02
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      sql: string
                      records:
                        - AlmacenID: 5
                          Codigo: SA01
                          Nombre: Silos Maiz 01
                        - AlmacenID: 6
                          Codigo: SF01
                          Nombre: Silo Forraje 01JUJJU
                        - AlmacenID: 7
                          Codigo: SS01
                          Nombre: Silo Semola 01
                        - AlmacenID: 39
                          Codigo: SA02
                          Nombre: Silos Maiz 02
                        - AlmacenID: 40
                          Codigo: SA03
                          Nombre: Silos Maiz 03
                        - AlmacenID: 41
                          Codigo: SA04
                          Nombre: Silos Maiz 04
                        - AlmacenID: 42
                          Codigo: SA05
                          Nombre: Silos Maiz 05
                        - AlmacenID: 43
                          Codigo: SA06
                          Nombre: Silos Maiz 06
                        - AlmacenID: 44
                          Codigo: SA07
                          Nombre: Silos Maiz 07
                        - AlmacenID: 46
                          Codigo: SS02
                          Nombre: Silo Semola 02
      operationId: get-warehouse
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcyMzQ5MTcyLCAiZXhwIjoxNjcyMzU2MzcyIH0._R6egSIjKnI-OMeQjVs5tz7Jk4vJSIdk7Wh22SyJomg
          in: header
          name: 'accessToken '
          description: Token de acceso. Si no se cuenta con uno no se podrá realizar la petición.
          required: true
        - schema:
            type: string
            example: silo
          in: query
          name: param
          description: Parámetro a buscar
  /warehouse/light:
    get:
      summary: FindLightList
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      Almacens:
                        type: array
                        items:
                          type: object
                          properties:
                            AlmacenID:
                              type: integer
                            Codigo:
                              type: string
                            Nombre:
                              type: string
                      almacenPrincipalID:
                        type: integer
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      Almacens:
                        - AlmacenID: 3
                          Codigo: Q1-MPE
                          Nombre: Calidad MP ME
                        - AlmacenID: 4
                          Codigo: MP
                          Nombre: Materia Prima
                        - AlmacenID: 5
                          Codigo: SA01
                          Nombre: Silos Maiz 01
                        - AlmacenID: 6
                          Codigo: SF01
                          Nombre: Silo Forraje 01JUJJU
                        - AlmacenID: 7
                          Codigo: SS01
                          Nombre: Silo Semola 01
                        - AlmacenID: 8
                          Codigo: SP01
                          Nombre: Subproductos
                        - AlmacenID: 9
                          Codigo: RECEP
                          Nombre: Recepción
                        - AlmacenID: 12
                          Codigo: MRO
                          Nombre: MRO
                        - AlmacenID: 13
                          Codigo: EPP
                          Nombre: EQUIPO PROTECCION PERSONAL
                        - AlmacenID: 15
                          Codigo: CEDISTEO
                          Nombre: CEDIS TEOLOYUCAN
                      almacenPrincipalID: 3
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      Almacens:
                        - AlmacenID: 3
                          Codigo: Q1-MPE
                          Nombre: Calidad MP ME
                        - AlmacenID: 4
                          Codigo: MP
                          Nombre: Materia Prima
                        - AlmacenID: 5
                          Codigo: SA01
                          Nombre: Silos Maiz 01
                        - AlmacenID: 6
                          Codigo: SF01
                          Nombre: Silo Forraje 01JUJJU
                        - AlmacenID: 7
                          Codigo: SS01
                          Nombre: Silo Semola 01
                        - AlmacenID: 8
                          Codigo: SP01
                          Nombre: Subproductos
                        - AlmacenID: 9
                          Codigo: RECEP
                          Nombre: Recepción
                        - AlmacenID: 12
                          Codigo: MRO
                          Nombre: MRO
                        - AlmacenID: 13
                          Codigo: EPP
                          Nombre: EQUIPO PROTECCION PERSONAL
                        - AlmacenID: 15
                          Codigo: CEDISTEO
                          Nombre: CEDIS TEOLOYUCAN
                      almacenPrincipalID: 3
      operationId: get-warehouse-light
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcyMzQ5MTcyLCAiZXhwIjoxNjcyMzU2MzcyIH0._R6egSIjKnI-OMeQjVs5tz7Jk4vJSIdk7Wh22SyJomg
          in: header
          name: accessToken
          description: Token de acceso. Si no se cuenta con uno no se podrá realizar la petición.
          required: true
  '/material/warehouse/{materialID}':
    parameters:
      - schema:
          type: string
          example: '246'
        name: materialID
        in: path
        required: true
        description: ArticuloID
    get:
      summary: FindManyForMaterial
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      success:
                        type: boolean
                      sql:
                        type: string
                      records:
                        type: array
                        items:
                          type: object
                          properties:
                            contador:
                              type: integer
                            ID:
                              type: integer
                            Nombre:
                              type: string
                            Codigo:
                              type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      sql: ''
                      records:
                        - contador: 1
                        - ID: 3
                          Nombre: Calidad MP ME
                          Codigo: Q1-MPE
                          contador: 2
                        - ID: 4
                          Nombre: Materia Prima
                          Codigo: MP
                          contador: 3
                        - contador: 4
                        - ID: 12
                          Nombre: MRO
                          Codigo: MRO
                          contador: 5
                        - ID: 13
                          Nombre: EQUIPO PROTECCION PERSONAL
                          Codigo: EPP
                          contador: 6
                        - contador: 7
                        - ID: 15
                          Nombre: CEDIS TEOLOYUCAN
                          Codigo: CEDISTEO
                          contador: 8
                        - ID: 16
                          Nombre: CEDIS AGUASCALIENTES
                          Codigo: CEDISAG
                          contador: 9
                        - ID: 17
                          Nombre: CEDIS VILLA HERMOSA
                          Codigo: CEDISVH
                          contador: 10
                        - ID: 18
                          Nombre: Producto terminado Sin Validar
                          Codigo: PT01
                          contador: 11
                        - ID: 19
                          Nombre: Producto terminado
                          Codigo: PT02
                          contador: 12
                        - ID: 28
                          Nombre: Granel A
                          Codigo: PQ-GRA_A
                          contador: 13
              examples:
                Example 1:
                  value:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      success: true
                      sql: ''
                      records:
                        - contador: 1
                        - ID: 3
                          Nombre: Calidad MP ME
                          Codigo: Q1-MPE
                          contador: 2
                        - ID: 4
                          Nombre: Materia Prima
                          Codigo: MP
                          contador: 3
                        - contador: 4
                        - ID: 12
                          Nombre: MRO
                          Codigo: MRO
                          contador: 5
                        - ID: 13
                          Nombre: EQUIPO PROTECCION PERSONAL
                          Codigo: EPP
                          contador: 6
                        - contador: 7
                        - ID: 15
                          Nombre: CEDIS TEOLOYUCAN
                          Codigo: CEDISTEO
                          contador: 8
                        - ID: 16
                          Nombre: CEDIS AGUASCALIENTES
                          Codigo: CEDISAG
                          contador: 9
                        - ID: 17
                          Nombre: CEDIS VILLA HERMOSA
                          Codigo: CEDISVH
                          contador: 10
                        - ID: 18
                          Nombre: Producto terminado Sin Validar
                          Codigo: PT01
                          contador: 11
                        - ID: 19
                          Nombre: Producto terminado
                          Codigo: PT02
                          contador: 12
                        - ID: 28
                          Nombre: Granel A
                          Codigo: PQ-GRA_A
                          contador: 13
      operationId: get-material-warehouse-materialID
      parameters:
        - schema:
            type: string
            example: eyAidHlwIjoiSldUIiwgImFsZyI6IkhTMjU2IiB9.eyAidXNlcklEIjoiMSIsICJjdXN0b21lcklEIjoiMjkiLCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJBRE1JTklTVFJBRE9SIiwgImFkbWluaXN0cmFkb3IiOiIxIiwgImVtcHJlc2FJRCI6IjEiLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjcyMzQ5MTcyLCAiZXhwIjoxNjcyMzU2MzcyIH0._R6egSIjKnI-OMeQjVs5tz7Jk4vJSIdk7Wh22SyJomg
          in: header
          name: accessToken
          description: Token de acceso. Si no se cuenta con uno no se podrá realizar la petición.
          required: true
      description: Busca en la tabla ArticuloXAlmacen por ArticuloID
  /families/lightlist:
    get:
      summary: Families - FindLightList
      tags: []
      responses: {}
      operationId: get-families-lightlist
  /families/manybyparam:
    get:
      summary: Families - FindManyByParam
      tags: []
      responses: {}
      operationId: get-families-manybyparam
  /families/validate:
    get:
      summary: Families - Validate
      tags: []
      responses: {}
      operationId: get-families-validate
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: dtlyuovycj0o3
