openapi: 3.0.0
info:
  version: '1.0'
  title: displayEvents
  description: ''
#paths: {}
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  # description: The number of items to skip before starting to collect the result set
  # Added by API Auto Mocking Plugin

  # Added by API Auto Mocking Plugin
  - description: Direccion pruebas España
    url: https://apifluxuadev.onyxsoft.co:8087 #/v1/sync/tasks/:taskID

    
paths:
  /endponint1:
    post:
      tags:
      - "pos1"
      summary: ""
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              properties:
                authorization:  
                  type: "string"
                  example: "eyAic2lnIjoiSFMyNTYiLCAidHlwIjoiSldUIiB9.eyAidXNlcklEIjo0NCwgImN1c3RvbWVySUQiOjI5LCAicnV0YUZvdG8iOiIiLCAidXNlck5hbWUiOiJlZGdvcyIsICJhZG1pbmlzdHJhZG9yIjp0cnVlLCAiZW1wcmVzYUlEIjoxLCAiYXBpS2V5IjoibWlzZWNyZXRpdG8iLCAiaWF0IjoxNjQ5MjU0ODMyLCAiZXhwIjoxNjQ5MjYyMDMyIH0.rNNdNm9MflATkqiE6tA_HOCb8BmMX6uleG1I_TY7AkU"
                empleadoID:
                  type: "integer"
                  example: "1"
                IDEmpleadoEvento:
                  type: "integer"
                  example: "2"
                color:
                  type: "string"
                  example: "10066431"
                dueno:
                  type: "string"
                  example: "Mis eventos"
                FechaIni:
                  type: "string"
                  format: "date"
                  example: "20-03-2022"
                FechaFin:
                  type: "string"
                  format: "date"
                  example: "20-03-2022"
      responses:
        200:
          description: True/False
        400:
          description: Error en caso de que success sea False
  
 
          
          