openapi: 3.0.0
info:
  version: '1.0'
  title: login
  description: ''
#paths: {}
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  # description: The number of items to skip before starting to collect the result set
  # Added by API Auto Mocking Plugin

  # Added by API Auto Mocking Plugin
  - description: Direccion pruebas España
    url: https://apifluxuadev.onyxsoft.co:8087 #/v1/sync/tasks/:taskID

    
paths:
  /v1/sync/tasks/a8ef3573-f91f-417a-95fa-b825cbcc400f:
    post:
      tags:
      - "pos1"
      summary: ""
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              properties:
                email:  
                  type: "string"
                  example: "admin@admin.com"
                password:
                  type: "string"
                  example: "0nyx2021"
                apiKey:
                  type: "string"
                  example: "misecretito"
      responses:
        200:
          description: True/False
        400:
          description: Error en caso de que success sea False
  
 
          
          