openapi: 3.1.0
x-stoplight:
  id: auxrtg87czh25
info:
  title: API-ProcesoGasto
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: qhd3hvzjoe2fm
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: dl67adzo3nok6
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: 9e8hjsl63ba5e
  /procesogasto:
    post:
      summary: ProcesoGastoCreate
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: post-procesogasto
      x-stoplight:
        id: s82n2zcn5ag56
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: token login
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Cantidad:
                  type: string
                EmpleadoID:
                  type: string
                ExcluirDePago:
                  type: string
                Fecha:
                  type: string
                FechaHoraPagado:
                  type: string
                Importe:
                  type: string
                Notas:
                  type: string
                Precio:
                  type: string
                ProcesoGastoID:
                  type: string
                ProcesoID:
                  type: string
                TiempoTrabajoID:
                  type: string
                TipoProcesoGastoID:
                  type: string
                UsuarioPagoID:
                  type: string
                WebID:
                  type: string
              x-examples:
                Example 1:
                  Cantidad: '3'
                  EmpleadoID: ''
                  ExcluirDePago: ''
                  Fecha: ''
                  FechaHoraPagado: ''
                  Importe: ''
                  Notas: ''
                  Precio: ''
                  ProcesoGastoID: ''
                  ProcesoID: ''
                  TiempoTrabajoID: ''
                  TipoProcesoGastoID: ''
                  UsuarioPagoID: ''
                  WebID: ''
  '/procesogasto/{ProcesoGastoID}':
    parameters:
      - schema:
          type: string
        name: ProcesoGastoID
        in: path
        required: true
      - schema:
          type: string
        name: ProcesoGastoID
        in: path
        required: true
      - schema:
          type: string
        name: ProcesoGastoID
        in: path
        required: true
    put:
      summary: ProcesoGastoUpdate
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: put-procesogasto-ProcesoGastoID
      x-stoplight:
        id: jhzdhmrxv7lol
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: token login
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Cantidad:
                  type: string
                EmpleadoID:
                  type: string
                ExcluirDePago:
                  type: string
                Fecha:
                  type: string
                FechaHoraPagado:
                  type: string
                Importe:
                  type: string
                Notas:
                  type: string
                Precio:
                  type: string
                ProcesoGastoID:
                  type: string
                ProcesoID:
                  type: string
                TiempoTrabajoID:
                  type: string
                TipoProcesoGastoID:
                  type: string
                UsuarioPagoID:
                  type: string
                WebID:
                  type: string
              x-examples:
                Example 1:
                  Cantidad: ''
                  EmpleadoID: ''
                  ExcluirDePago: ''
                  Fecha: ''
                  FechaHoraPagado: ''
                  Importe: ''
                  Notas: ''
                  Precio: ''
                  ProcesoGastoID: ''
                  ProcesoID: ''
                  TiempoTrabajoID: ''
                  TipoProcesoGastoID: ''
                  UsuarioPagoID: ''
                  WebID: ''
    delete:
      summary: ProcesoGastoDelete
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties: {}
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: delete-procesogasto-ProcesoGastoID
      x-stoplight:
        id: ikfazro2smiq2
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: token login
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: q04vghfx2nfy0
        firstName:
          type: string
          x-stoplight:
            id: 1bqiqor5pyluz
        lastName:
          type: string
          x-stoplight:
            id: 3k90cg2zdamrj
        email:
          type: string
          format: email
          x-stoplight:
            id: v7vlojy7v2g8u
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 6581mndco4m16
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: wjrzxnyryydrk
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: j3wr15ik1450q
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: hkia6jfnkby27
