openapi: 3.1.0
x-stoplight:
  id: 2nexftudgc3uf
info:
  title: API-Proceso
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: 34k5pq03koqn8
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: aswxo9i63xqj7
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: i0p11ayc5xh8k
  /proceso:
    get:
      summary: Proceso Find Many
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        Bufferpreparacion:
                          type: integer
                        CantidadFabricacion:
                          type: integer
                        CantidadPrevista:
                          type: integer
                        CantidadRechazada:
                          type: integer
                        CantidadTransferencia:
                          type: integer
                        Capitulo:
                          type: string
                        CosteExteriorPresupuestado:
                          type: integer
                        CosteManoObraPresupuestado:
                          type: integer
                        CosteMaterialesPresupuestado:
                          type: integer
                        CosteOtrosPresupuestado:
                          type: integer
                        CustomerID:
                          type: integer
                        DescripcionAmpliada:
                          type: string
                        EmpleadoID:
                          type: integer
                        EmpleadoTipoPuestoID:
                          type: integer
                        EmpresaID:
                          type: integer
                        EsObraOf:
                          type: string
                        Estado:
                          type: string
                        Externo:
                          type: integer
                        FechaHoraFin:
                          type: string
                        FechaHoraFinPlanificacion:
                          type: string
                        FechaHoraFinProgramada:
                          type: string
                        FechaHoraInicio:
                          type: string
                        FechaHoraInicioPlanificacion:
                          type: string
                        FechaHoraInicioProgramada:
                          type: string
                        FechaHoraModificado:
                          type: string
                        FechaHoraUsuario:
                          type: string
                        Hito:
                          type: integer
                        ImporteExterno:
                          type: integer
                        Limitante:
                          type: integer
                        MaquinaID:
                          type: integer
                        MaquinaObligatoria:
                          type: integer
                        MotivoRetencion:
                          type: string
                        Nombre:
                          type: string
                        NumeroOrden:
                          type: integer
                        NumeroProceso:
                          type: integer
                        OperacionID:
                          type: integer
                        Orden:
                          type: integer
                        OrdenMaquina:
                          type: integer
                        Partida:
                          type: integer
                        PedidoVentaLineaID:
                          type: integer
                        PrecioExterno:
                          type: integer
                        ProcesoID:
                          type: integer
                        ProcesoPadreID:
                          type: integer
                        ProcesoRecuperacion:
                          type: integer
                        Productiva:
                          type: integer
                        ProveedorID:
                          type: integer
                        Proyecto_OFID:
                          type: integer
                        Retenido:
                          type: integer
                        RutaFabricacionOperacionID:
                          type: integer
                        SeccionID:
                          type: integer
                        Tiempo:
                          type: integer
                        TiempoPreparacionPrevisto:
                          type: integer
                        TiempoPreparacionReal:
                          type: integer
                        TiempoProduccionAsignado:
                          type: integer
                        TiempoProduccionOperarioPrevisto:
                          type: integer
                        TiempoProduccionPrevisto:
                          type: integer
                        TiempoProduccionReal:
                          type: integer
                        TipoProcesoID:
                          type: integer
                        UltimoProceso:
                          type: integer
                        UnidadMedidaID:
                          type: integer
                        UsuarioID:
                          type: integer
                        UsuarioIDCierre:
                          type: integer
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      - Bufferpreparacion: 0
                        CantidadFabricacion: 0
                        CantidadPrevista: 0
                        CantidadRechazada: 0
                        CantidadTransferencia: 0
                        Capitulo: ''
                        CosteExteriorPresupuestado: 0
                        CosteManoObraPresupuestado: 0
                        CosteMaterialesPresupuestado: 0
                        CosteOtrosPresupuestado: 0
                        CustomerID: 29
                        DescripcionAmpliada: ''
                        EmpleadoID: 13
                        EmpleadoTipoPuestoID: 0
                        EmpresaID: 1
                        EsObraOf: M
                        Estado: FI
                        Externo: 0
                        FechaHoraFin: '0000-00-00T00:00:00.000'
                        FechaHoraFinPlanificacion: '2020-08-12T13:07:00.000'
                        FechaHoraFinProgramada: '0000-00-00T00:00:00.000'
                        FechaHoraInicio: '0000-00-00T00:00:00.000'
                        FechaHoraInicioPlanificacion: '2020-08-12T13:07:00.000'
                        FechaHoraInicioProgramada: '0000-00-00T00:00:00.000'
                        FechaHoraModificado: '2020-08-12T20:07:13.000'
                        FechaHoraUsuario: '2020-08-12T13:09:31.000'
                        Hito: 0
                        ImporteExterno: 0
                        Limitante: 0
                        MaquinaID: 0
                        MaquinaObligatoria: 0
                        MotivoRetencion: ''
                        Nombre: ''
                        NumeroOrden: 0
                        NumeroProceso: 38
                        OperacionID: 0
                        Orden: 0
                        OrdenMaquina: 0
                        Partida: 0
                        PedidoVentaLineaID: 0
                        PrecioExterno: 0
                        ProcesoID: 4958
                        ProcesoPadreID: 0
                        ProcesoRecuperacion: 0
                        Productiva: 1
                        ProveedorID: 0
                        Proyecto_OFID: 926
                        Retenido: 0
                        RutaFabricacionOperacionID: 0
                        SeccionID: 0
                        Tiempo: 0
                        TiempoPreparacionPrevisto: 0
                        TiempoPreparacionReal: 0
                        TiempoProduccionAsignado: 0
                        TiempoProduccionOperarioPrevisto: 0
                        TiempoProduccionPrevisto: 3536149
                        TiempoProduccionReal: 0
                        TipoProcesoID: 0
                        UltimoProceso: 0
                        UnidadMedidaID: 0
                        UsuarioID: 2
                        UsuarioIDCierre: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: get-proceso
      x-stoplight:
        id: 00pr0vo93b7oa
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: login token
          required: true
        - schema:
            type: string
          in: query
          name: ProyectoOFID
        - schema:
            type: array
          in: query
          name: Estado
          description: 'lista ( , )'
        - schema:
            type: string
          in: query
          name: NumeroProceso
        - schema:
            type: string
          in: query
          name: Nombre
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: z3thdq1ugdx0z
        firstName:
          type: string
          x-stoplight:
            id: ohnohcknthglz
        lastName:
          type: string
          x-stoplight:
            id: q6gnftg8dacaf
        email:
          type: string
          format: email
          x-stoplight:
            id: 4jkmhy8z38wwy
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: tvrnghqzl58pq
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: ctbhfaulyz6p0
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: u4kyski23r7fj
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: ox3npnytbfmfa
