openapi: 3.1.0
x-stoplight:
  id: d3lumlet7sj8g
info:
  title: ApiUbications
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /consult/ubications:
    get:
      summary: findManyByFilters
      tags: []
      responses:
        '200':
          description: '{ "statusCode":200, "message":"Request processed successfully", "content":{ "records":[ { "DireccionID":13, "Codigo":1, "Nombre":"SAT MADRID 1", "Direccion":"Calle de los comuneros de Castilla, 18", "Municipio":"MADRID", "CodigoPostal":"28000", "Pais":"Espa\u00f1a", "Provincia":"Araba", "CodigoCliente":"43000001", "NombreCliente":"dario", "Telefono":"3218316754", "Email":"", "codigoContrato":"", "NombreContrato":"" }, { "DireccionID":14, "Codigo":2, "Nombre":"ANER VITORIA", "Direccion":"Zumar Hiribidea, 1", "Municipio":"", "CodigoPostal":"", "Pais":"Espa\u00f1a", "Provincia":"Araba", "CodigoCliente":"43000001", "NombreCliente":"dario", "Telefono":"3218316754", "Email":"", "codigoContrato":"", "NombreContrato":"" }, { "DireccionID":52, "Codigo":46, "Nombre":"wewe", "Direccion":"", "Municipio":"", "CodigoPostal":"", "Pais":"", "Provincia":"", "CodigoCliente":"43000001", "NombreCliente":"dario", "Telefono":"", "Email":"", "codigoContrato":"", "NombreContrato":"" } ], "sql":"SELECT DISTINCT Direccion.*,\r\nPais.Nombre AS NombrePais,\r\nProvincia.Nombre AS NombreProvincia,\r\nCodigoPostal.CodigoPostal AS NombreCodigoPostal,\r\nMailing.ReferenciaCodigo AS CodigoMailing,\r\nMailing.Nombre AS NombreMailing \r\nFROM Direccion\r\nLEFT OUTER JOIN Elemento ON Elemento.DireccionID = Direccion.DireccionID\r\nLEFT OUTER JOIN Pais ON Pais.PaisID = Direccion.PaisID\r\nLEFT OUTER JOIN Provincia ON Provincia.ProvinciaID = Direccion.ProvinciaID\r\nLEFT OUTER JOIN CodigoPostal ON CodigoPostal.CodigoPostalID = Direccion.CodigoPostalID\r\nLEFT OUTER JOIN Mailing ON Mailing.MailingID = Direccion.MailingID\r\nWHERE Direccion.CustomerID = 29\r\nAND Direccion.EmpresaID = 1\r\nAND Direccion.Clave IN (''SAT'')\r\n AND (Direccion.MailingID IN (4))\r\nlimit 50 \r\noffset 0", "success":true } } '
      operationId: get-consult-ubications
      parameters:
        - schema:
            type: string
          in: header
          name: 'accessToken '
          description: '"tokenReciente"'
        - schema:
            type: integer
          in: query
          name: offset
          description: '0'
        - schema:
            type: integer
          in: query
          name: limit
          description: '50'
        - schema:
            type: string
          in: query
          name: codigoInferior
        - schema:
            type: string
          in: query
          name: codigoSuperior
        - schema:
            type: string
          in: query
          name: Ubicacion
        - schema:
            type: string
          in: query
          name: direccion
        - schema:
            type: string
          in: query
          name: mailingID
          description: '4'
        - schema:
            type: string
          in: query
          name: contratoID
        - schema:
            type: string
          in: query
          name: equipoID
        - schema:
            type: string
          in: query
          name: Municipio
        - schema:
            type: string
          in: query
          name: codigoPostal
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
