openapi: 3.0.0
x-stoplight:
  id: 3nhwpnthwvrno
info:
  title: ApiInterventions
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/intervention/material/{procesoID}':
    parameters:
      - schema:
          type: string
        name: procesoID
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  TipoMovimientoID:
                    type: string
                  ReservaMaterialID:
                    type: string
                  Fecha:
                    type: string
                  AlmacenID:
                    type: string
                  ArticuloID:
                    type: string
                  MailingID:
                    type: string
                  CantidadAlmacen:
                    type: string
                  CantidadPrecio:
                    type: string
                  Precio:
                    type: string
                  Concepto:
                    type: string
                  FicheroOrigen:
                    type: string
                  IndiceUnico:
                    type: string
                  Hora:
                    type: string
                  ProcesoID:
                    type: string
                  ExcluirInventario:
                    type: string
                  FechaHoraModificado:
                    type: string
                  Factor:
                    type: string
                  FechaHora:
                    type: string
                  ExistenciaUbicacionLoteID:
                    type: string
                  Cantidad2:
                    type: string
                  ArticuloXAlmacenID:
                    type: string
                  GastoCompra:
                    type: string
                  EmpleadoID:
                    type: string
                  FactorCantidad:
                    type: string
                  GastoCompraCantidad2:
                    type: string
                  UsuarioVerificacionID:
                    type: string
                  FechaHoraVerificacion:
                    type: string
                  EmpleadoVerificacionID:
                    type: string
                  CuentaVerificacionID:
                    type: string
                  IncidenciaCalidadCabeceraID:
                    type: string
                  WebID:
                    type: string
                  ProcesoUtillajeID:
                    type: string
                x-examples:
                  Example 1:
                    TipoMovimientoID: '4'
                    ReservaMaterialID: '4789'
                    Fecha: '20230224'
                    AlmacenID: '2'
                    ArticuloID: '555'
                    MailingID: '873'
                    CantidadAlmacen: '10'
                    CantidadPrecio: '4'
                    Precio: '10'
                    Concepto: Intervención 16
                    FicheroOrigen: ReservaMaterial
                    IndiceUnico: '4759'
                    Hora: ''
                    ProcesoID: '5198'
                    ExcluirInventario: '0'
                    FechaHoraModificado: ''
                    Factor: '1'
                    FechaHora: ''
                    ExistenciaUbicacionLoteID: ''
                    Cantidad2: ''
                    ArticuloXAlmacenID: ''
                    GastoCompra: ''
                    EmpleadoID: ''
                    FactorCantidad: ''
                    GastoCompraCantidad2: ''
                    UsuarioVerificacionID: ''
                    FechaHoraVerificacion: ''
                    EmpleadoVerificacionID: ''
                    CuentaVerificacionID: ''
                    IncidenciaCalidadCabeceraID: ''
                    WebID: ''
                    ProcesoUtillajeID: ''
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
        - schema:
            type: string
          in: query
          name: procesoID
          description: ID del Proceso
  /intervention/material:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                TipoMovimientoID:
                  type: string
                ReservaMaterialID:
                  type: string
                Fecha:
                  type: string
                AlmacenID:
                  type: string
                ArticuloID:
                  type: string
                MailingID:
                  type: string
                CantidadAlmacen:
                  type: string
                CantidadPrecio:
                  type: string
                Precio:
                  type: string
                Concepto:
                  type: string
                FicheroOrigen:
                  type: string
                IndiceUnico:
                  type: string
                Hora:
                  type: string
                ProcesoID:
                  type: string
                ExcluirInventario:
                  type: string
                FechaHoraModificado:
                  type: string
                Factor:
                  type: string
                FechaHora:
                  type: string
                ExistenciaUbicacionLoteID:
                  type: string
                Cantidad2:
                  type: string
                ArticuloXAlmacenID:
                  type: string
                GastoCompra:
                  type: string
                EmpleadoID:
                  type: string
                FactorCantidad:
                  type: string
                GastoCompraCantidad2:
                  type: string
                UsuarioVerificacionID:
                  type: string
                FechaHoraVerificacion:
                  type: string
                EmpleadoVerificacionID:
                  type: string
                CuentaVerificacionID:
                  type: string
                IncidenciaCalidadCabeceraID:
                  type: string
                WebID:
                  type: string
                ProcesoUtillajeID:
                  type: string
              x-examples:
                Example 1:
                  TipoMovimientoID: '4'
                  ReservaMaterialID: '4789'
                  Fecha: '20230224'
                  AlmacenID: '2'
                  ArticuloID: '555'
                  MailingID: '873'
                  CantidadAlmacen: '10'
                  CantidadPrecio: '4'
                  Precio: '10'
                  Concepto: Intervención 16
                  FicheroOrigen: ReservaMaterial
                  IndiceUnico: '4759'
                  Hora: ''
                  ProcesoID: '5198'
                  ExcluirInventario: '0'
                  FechaHoraModificado: ''
                  Factor: '1'
                  FechaHora: ''
                  ExistenciaUbicacionLoteID: ''
                  Cantidad2: ''
                  ArticuloXAlmacenID: ''
                  GastoCompra: ''
                  EmpleadoID: ''
                  FactorCantidad: ''
                  GastoCompraCantidad2: ''
                  UsuarioVerificacionID: ''
                  FechaHoraVerificacion: ''
                  EmpleadoVerificacionID: ''
                  CuentaVerificacionID: ''
                  IncidenciaCalidadCabeceraID: ''
                  WebID: ''
                  ProcesoUtillajeID: ''
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
    parameters: []
  '/intervention/material/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-intervention-material-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  MovimientoAlmacenID:
                    type: string
                  TipoMovimientoID:
                    type: string
                  ReservaMaterialID:
                    type: string
                  Fecha:
                    type: string
                  AlmacenID:
                    type: string
                  ArticuloID:
                    type: string
                  MailingID:
                    type: string
                  CantidadAlmacen:
                    type: string
                  CantidadPrecio:
                    type: string
                  Precio:
                    type: string
                  Concepto:
                    type: string
                  FicheroOrigen:
                    type: string
                  IndiceUnico:
                    type: string
                  Hora:
                    type: string
                  ProcesoID:
                    type: string
                  ExcluirInventario:
                    type: string
                  FechaHoraModificado:
                    type: string
                  Factor:
                    type: string
                  FechaHora:
                    type: string
                  ExistenciaUbicacionLoteID:
                    type: string
                  Cantidad2:
                    type: string
                  ArticuloXAlmacenID:
                    type: string
                  GastoCompra:
                    type: string
                  EmpleadoID:
                    type: string
                  FactorCantidad:
                    type: string
                  GastoCompraCantidad2:
                    type: string
                  UsuarioVerificacionID:
                    type: string
                  FechaHoraVerificacion:
                    type: string
                  EmpleadoVerificacionID:
                    type: string
                  CuentaVerificacionID:
                    type: string
                  IncidenciaCalidadCabeceraID:
                    type: string
                  WebID:
                    type: string
                  ProcesoUtillajeID:
                    type: string
                x-examples:
                  Example 1:
                    MovimientoAlmacenID: '35093'
                    TipoMovimientoID: '4'
                    ReservaMaterialID: '4789'
                    Fecha: '20230224'
                    AlmacenID: '2'
                    ArticuloID: '555'
                    MailingID: '873'
                    CantidadAlmacen: '10'
                    CantidadPrecio: '4'
                    Precio: '10'
                    Concepto: Intervención 16
                    FicheroOrigen: ReservaMaterial
                    IndiceUnico: '4759'
                    Hora: ''
                    ProcesoID: '5198'
                    ExcluirInventario: '0'
                    FechaHoraModificado: ''
                    Factor: '1'
                    FechaHora: ''
                    ExistenciaUbicacionLoteID: ''
                    Cantidad2: ''
                    ArticuloXAlmacenID: ''
                    GastoCompra: ''
                    EmpleadoID: ''
                    FactorCantidad: ''
                    GastoCompraCantidad2: ''
                    UsuarioVerificacionID: ''
                    FechaHoraVerificacion: ''
                    EmpleadoVerificacionID: ''
                    CuentaVerificacionID: ''
                    IncidenciaCalidadCabeceraID: ''
                    WebID: ''
                    ProcesoUtillajeID: ''
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
        - schema:
            type: string
          in: query
          name: id
          description: ID del Movimiento Almacen
    delete:
      summary: ''
      operationId: delete-intervention-material-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  MovimientoAlmacenID:
                    type: string
                x-examples:
                  Example 1:
                    MovimientoAlmacenID: '35093'
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
        - schema:
            type: string
          in: query
          name: id
          description: ID del Movimiento Almacen
      description: ''
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
